#Options for interface configuration
#UART settings
- name          : no_uart
  description   : Disable UART
  type          : Boolean
  defaultValue  : False
  access        : True

- name          : uart_name
  description   : UART name
  type          : OptionList
  defaultValue  : "serial"
  options       : ["serial", "uart"]
  access        : True
  
#This does not need to be an OptionList, but it seems sensible to just offer standard rates
- name          : uart_baudrate
  description   : UART baudrate
  type          : OptionList
  defaultValue  : 115200
  options       : [230400, 115200, 57600, 38400, 19200, 9600]

#LiteX generic interfaces
- name          : soft_i2c
  description   : Use software I2C
  type          : Boolean
  defaultValue  : False
  access        : True

- name          : hard_i2c
  description   : Use hardware I2C
  type          : Boolean
  defaultValue  : False
  access        : True

- name          : soft_spi
  description   : Use software SPI
  type          : Boolean
  defaultValue  : False
  access        : True

- name          : hard_spi
  description   : Use hardware SPI
  type          : Boolean
  defaultValue  : False
  access        : True

- name          : SDcard
  description   : Use SDcard
  type          : Boolean
  defaultValue  : False
  access        : True

#CSR Settings
- name          : csr_data_width
  description   : CSR data width in bits
  type          : Integer
  defaultValue  : 32
  access        : True

- name          : csr_address_width
  description   : CSR address width in bits
  type          : Integer
  defaultValue  : 14
  access        : True

- name          : csr_paging
  description   : CSR paging
  type          : Integer
  defaultValue  : 2048
  access        : True

- name          : csr_ordering
  description   : CSR ordering
  type          : OptionList
  defaultValue  : "big"
  options       : ["big", "little"]
  access        : True

#Settings related to system bus interfaces

- name          : external_bus_master_interface
  description   : Add external bus master interface (SoC -> Periphery)
  type          : Boolean
  defaultValue  : False
  access        : True

- name          : external_bus_slave_interface
  description   : Add external bus slave interface (Periphery -> SoC)
  type          : Boolean
  defaultValue  : False
  access        : True

- name          : external_bus_region_origin
  description   : Origin of external bus region
  type          : OpenString
  defaultValue  : 0xa0000000
  access        : True

- name          : external_bus_region_size
  description   : Size of external bus region
  type          : OpenString
  defaultValue  : 0x10000000
  access        : True

- name          : external_bus_region_cached
  description   : Activate cache for external bus region
  type          : Boolean
  defaultValue  : False
  access        : True