using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Acornima.Ast;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Platform;
using Avalonia.Platform.Storage;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Jint.Runtime;
using YamlDotNet.Core;
using YamlDotNet.Core.Events;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace systembuilderGUI.Models;

public partial class ConfigFile : ObservableObject
{
    public IStorageProvider? StorageProvider { get; set; }
    
    public ConfigFile()
    {
        CoreItems = initItems(new Uri("avares://systembuilderGUI/Assets/configuration_coreItems_definition.yaml"));
        Interfaces = initItems(new Uri("avares://systembuilderGUI/Assets/configuration_interfaces_definition.yaml"));
    }
    public ObservableCollection<ConfigItem> CoreItems { get; set; } = new();
    public ObservableCollection<ConfigItem> Interfaces { get; set; } = new();
    public ObservableCollection<SubModule> subModules { get; set; } = new();
    
    [ObservableProperty] private string? outputDirPath;
    [ObservableProperty] private string? outputFilePath;
    [ObservableProperty] private string? logPath;
    
    private ObservableCollection<ConfigItem> initItems(Uri source)
    {
        using var stream = AssetLoader.Open(source);
        using var reader = new StreamReader(stream);
        var yml = reader.ReadToEnd();

        var deserializer = new DeserializerBuilder()
            .WithNamingConvention(YamlDotNet.Serialization.NamingConventions.CamelCaseNamingConvention.Instance)
            .Build();
        var returnItems = deserializer.Deserialize<ObservableCollection<ConfigItem>>(yml);

        foreach (var item in returnItems.Where(i => string.IsNullOrWhiteSpace(i.Value) && !string.IsNullOrWhiteSpace(i.DefaultValue)))
            item.Value = item.DefaultValue;
        
        return returnItems;
    }
    
    private string ToYaml(string outputType)
    {
        // Build dictionaries containing only name and value of configuration items
        var dictCoreItems = CoreItems
            .Where(item => item.Name is not null)
            .ToDictionary(item => item.Name, item => item.Value);
        
        var dictInterfaces = Interfaces
            .Where(item => item.Name is not null)
            .ToDictionary(item => item.Name, item => item.Value);
        
        var dictSubmodules = new Dictionary<dynamic, dynamic>();
        var valsSubmodules = subModules
            .Select((submod, index) => new { Index = index, Submod = submod })
            .Where(IdxSm => !string.IsNullOrWhiteSpace(IdxSm.Submod.Instance))
            .ToDictionary(
                x => "ext_mod_" + x.Index,
                x => x.Submod.ToDictionary(outputType)
            );
        dictSubmodules.Add("external_modules", valsSubmodules);

        var itemSerializer = new SerializerBuilder()
            .WithIndentedSequences()
            // .WithAttributeOverride<Port>(
            //     x => x.Width,
            //     new YamlMemberAttribute
            //     {
            //         ScalarStyle = ScalarStyle.DoubleQuoted
            //     }
            // )
            // ^^^ probably unneeded, needs testing
            .Build();

        var yml = "";

        if (outputType == "save")
        {
            yml +=
                "---\n" +
                "# This YAML file contains a saved configuration for the fentwums Systembuilder\n" +
                "# Do not edit this file\n" +
                "version: 1.0\n" +
                "---\n";
        } 

        yml += itemSerializer.Serialize(dictCoreItems);
        yml += itemSerializer.Serialize(dictInterfaces);
        yml += itemSerializer.Serialize(dictSubmodules);

        return yml;
    }
    
    private ConfigItem? FindItemByName(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return null;
        return CoreItems.FirstOrDefault(item => string.Equals(item.Name, name, StringComparison.OrdinalIgnoreCase))
               ?? Interfaces.FirstOrDefault(item => string.Equals(item.Name, name, StringComparison.OrdinalIgnoreCase));
    }

    public string? GetSOCName()
    {
        var nameItem = FindItemByName("Name");
        return nameItem?.Value;
    }

    
    public async Task GenerateSystemBuilderInput(string? path = null)
    {
        var nameItem = FindItemByName("Name");
        if (nameItem is null) throw new InvalidOperationException("No name was found in the SOC config file.");
        
        if (string.IsNullOrWhiteSpace(path))
        {
            var rootPath = Path.GetPathRoot(AppContext.BaseDirectory) ?? "C:\\";
            path = Path.Combine(rootPath, "fentwumsGUI", "systembuilder");
        }
        if (string.IsNullOrWhiteSpace(path)) throw new InvalidOperationException("No path was given to save the config file.");
        
        var filePath = Path.Combine(path, $"input_systembuilder_{nameItem.Value}.yaml");
        var logFilePath = Path.Combine(path, $"container_log_raw.txt");
        
        OutputDirPath = path;
        OutputFilePath = filePath;
        LogPath = logFilePath;

        if (!Directory.Exists(Path.GetDirectoryName(filePath)))
        {
            Directory.CreateDirectory(Path.GetDirectoryName(filePath));
        }

        await File.WriteAllTextAsync(logFilePath, "Container has not run yet.");
        
        var yml = ToYaml("build");
        
        await File.WriteAllTextAsync(filePath, yml);
        Debug.WriteLine($"Generated Litex input to {filePath}");
    }

    public async Task SaveConfiguration(string? path = null)
    {
        var nameItem = FindItemByName("Name");
        if (nameItem is null) throw new InvalidOperationException("No name was found in the SOC config file.");
        
        if (string.IsNullOrWhiteSpace(path))
        {
            var rootPath = Path.GetPathRoot(AppContext.BaseDirectory) ?? "C:\\";
            path = Path.Combine(rootPath, "fentwumsGUI", "systembuilder");
        }
        if (string.IsNullOrWhiteSpace(path)) throw new InvalidOperationException("No path was given to save the config file.");
        
        var filePath = Path.Combine(path, $"configFile_{nameItem.Value}.yaml");

        if (!Directory.Exists(Path.GetDirectoryName(filePath)))
        {
            Directory.CreateDirectory(Path.GetDirectoryName(filePath));
        }
        
        var yml = ToYaml("save");
        
        await File.WriteAllTextAsync(filePath, yml);
        Debug.WriteLine($"Saved configuration to {filePath}");
    }

    public async Task LoadConfiguration(string? path = null)
    {
        if (path is null || !File.Exists(path))
        {
            Debug.WriteLine($"Configuration file not found at {path}.");
            return;
        }

        var deserializer = new DeserializerBuilder()
            .WithNamingConvention(CamelCaseNamingConvention.Instance)
            .Build();

        using var reader = File.OpenText(path);
        var parser = new Parser(reader);

        parser.Consume<StreamStart>();

        if (!parser.TryConsume<DocumentStart>(out _))
            throw new InvalidDataException("YAML stream did not start with a document.");

        var header = deserializer.Deserialize<Dictionary<string, object>>(parser);

        var version = header.TryGetValue("version", out var vObj) ? vObj.ToString() : null;

        if (version is null)
            throw new InvalidDataException("Missing 'version' property.");

        var supportedVersions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "1.0"
        };

        if (!supportedVersions.Contains(version))
            throw new InvalidDataException(
                $"Unsupported configuration version: {version}. Supported versions are: {string.Join(", ", supportedVersions)}");

        parser.Consume<DocumentEnd>();

        if (!parser.TryConsume<DocumentStart>(out _))
            throw new InvalidDataException("YAML stream missing second document (configuration).");

        var config = deserializer.Deserialize<Dictionary<string, object>>(parser);

        subModules.Clear();

        foreach (var entry in config)
        {
            if (entry.Key == "external_modules")
            {
                if (entry.Value is Dictionary<object, object> submodulesDict)
                {
                    foreach (var submoduleEntry in submodulesDict)
                    {
                        if (submoduleEntry.Value is Dictionary<object, object> submoduleData)
                        {
                            List<SubModule?>? addedSubModules = null;
                            if (submoduleData.TryGetValue("source", out var source))
                            {
                                addedSubModules = await AddSubModuleFromFile(source?.ToString() ?? string.Empty);
                            } else
                            {
                                Debug.WriteLine("Missing 'source' property.");
                                return;
                            }

                            if (addedSubModules is null || addedSubModules.Count == 0)
                            {
                                // TODO: Add proper error massage in OnwWare
                                Debug.WriteLine($"Failed to add submodule from source: {source?.ToString()}");
                                return;
                            }
                            
                            SubModule? subModuleToUpdate = null;
                            if (addedSubModules.Count > 1)
                            {
                                submoduleData.TryGetValue("module_name", out var moduleName);
                                foreach (var module in addedSubModules)
                                {
                                    if (module.Module.Name == moduleName?.ToString())
                                    {
                                        if (subModuleToUpdate is null)
                                        {
                                            subModuleToUpdate = module;
                                        }
                                        else
                                        {
                                            Debug.WriteLine($"Multiple modules with the same name ({moduleName}) found in source: {source?.ToString()}. Only the first one will be updated.");
                                            // TODO: Implement proper Error massage in OnwWare
                                        }
                                    }
                                    else
                                    {
                                        subModules.Remove(module);
                                    }
                                }
                                Debug.WriteLine($"Multiple submodules found in source: {source?.ToString()}. Only module with matching name ({moduleName}) will be updated.");
                            }
                            else
                            {
                                subModuleToUpdate = addedSubModules.First();
                            }

                            if (subModuleToUpdate is null)
                            {
                                Debug.WriteLine("No matching module found in source");
                                return;
                            }
                            
                            foreach (var kvp in submoduleData)
                            {
                                var key = kvp.Key.ToString();
                                var value = kvp.Value;

                                switch (key)
                                {
                                    case "instance_name":
                                        subModuleToUpdate.Instance = value.ToString();
                                        break;
                                    case "isExternalModule":
                                        if (bool.TryParse(value.ToString(), out bool isExternal))
                                            subModuleToUpdate.IsExternalModule = isExternal;
                                        break;
                                    case "parameters":
                                        if (value is Dictionary<object, object> parametersDict)
                                        {
                                            foreach (var paramKvp in parametersDict)
                                            {
                                                var paramName = paramKvp.Key.ToString();
                                                var paramValue = paramKvp.Value?.ToString();

                                                var parameter = subModuleToUpdate.Module.Parameters.FirstOrDefault(p => p.Name == paramName);
                                                if (parameter is not null)
                                                {
                                                    parameter.Value = paramValue;
                                                }
                                            }
                                        }
                                        break;
                                    case "ports":
                                        if (value is Dictionary<object, object> portsDict)
                                        {
                                            foreach (var portDict in portsDict)
                                            {
                                                if (portDict.Value is Dictionary<object, object> portData)
                                                {
                                                    var portName = portData.TryGetValue("name", out var nameValue) ? nameValue.ToString() : null;
                                                    Debug.WriteLine($"Found Port : {portName}");
                                                    var routeToSOC = portData.TryGetValue("routeToSOC", out var routeToSOCValue) && bool.TryParse(routeToSOCValue.ToString(), out var soc) && soc;
                                                    var routeToWrapper = portData.TryGetValue("routeToWrapper", out var routeToWrapperValue) && bool.TryParse(routeToWrapperValue.ToString(), out var wrapper) && wrapper;

                                                    subModuleToUpdate.Module.Ports?.FirstOrDefault(p => p.Name == portName)?.SetRoute(routeToSOC, routeToWrapper);
                                                }
                                            }
                                        }
                                        break;
                                }
                            }
                        }
                    }
                }
            }
            else
            {
                var item = FindItemByName(entry.Key);
                if (item is not null)
                {
                    item.Value = entry.Value?.ToString();
                }
            }
        }
    }

    public async Task ChooseOutputDirectory(ConfigItem item)
    {
        if (item is null)
            return;

        var result = await StorageProvider.OpenFolderPickerAsync(new FolderPickerOpenOptions
        {
            Title = "Ordner auswählen",
            AllowMultiple = false
        });

        var folder = result?.FirstOrDefault();
        if (folder is not null)
        {
            var path = folder.TryGetLocalPath() ?? folder.Path.LocalPath;
            item.Value = path;
        }
    }
    
    public async Task<List<SubModule?>?> AddSubModuleFromFile(string filePath)
    {
        var AddedSubModules = new List<SubModule?>();
        
        if (string.IsNullOrWhiteSpace(filePath) || !File.Exists(filePath))
            return null;

        var verilogParser = new VerilogParser();
        var modules = verilogParser.ReadVerilog(filePath);

        if (modules.Count > 0)
        {
            foreach (var module in modules)
            {
                var instCnt = 0;
                var instanceName = $"{module.Name}_{instCnt}";

                while (subModules.Any(sm => sm.Instance == instanceName))
                {
                    instCnt++;
                    instanceName = $"{module.Name}_{instCnt}";
                }

                var subModule = new SubModule()
                {
                    Module = module,
                    Source = filePath,
                    Filename = Path.GetFileName(filePath),
                    Instance = instanceName,
                };

                subModules.Add(subModule);
                AddedSubModules.Add(subModule);
            }
        }
        return AddedSubModules;
    }

    public async Task CopySubmodule(SubModule subModule)
    {
        var instanceName = subModule.Instance;
        var baseInstanceName = instanceName;
        var number = 0;

        // Prüfe ob der Instanzname mit Zahlen endet
        var match = System.Text.RegularExpressions.Regex.Match(instanceName, @"_(\d+)$");
        if (match.Success)
        {
            baseInstanceName = instanceName[..match.Index];
            number = int.Parse(match.Groups[1].Value);
        }
        else
        {
            baseInstanceName = instanceName;
        }

        // Generiere einen eindeutigen Namen
        do
        {
            number++;
            instanceName = $"{baseInstanceName}_{number}";
        } while (subModules.Any(m => m.Instance == instanceName));

        // Erstelle eine Kopie des Moduls
        var newModule = new SubModule
        {
            Source = subModule.Source,
            Filename = subModule.Filename,
            Module = subModule.Module.Copy(),
            Instance = instanceName,
            IsExternalModule = subModule.IsExternalModule
        };

        subModules.Add(newModule);
    }
}